/**************

  Header:  Class.CH
  
           Header para Criacao de Classes
  
*/
/**************

 Definicao dos Metodos

*/
 
#xtranslate DEFINE CLASS <oClass> USING <exp,...>  =>;
            FUNCTION <oClass> ( <exp> )

#xtranslate DEFINE METHOD <cMethod> [MESSAGES <exp,...>]  =>;
            FUNCTION <cMethod> ( <exp> )           

#xtranslate OBJECT LOCAL <Object,...>     => LOCAL   <Object>
#xtranslate OBJECT STATIC <Object,...>    => STATIC  <Object>
