PROCEDURE TELADIR()
@  5, 23  SAY "[ ]Estoque         [ ]Relat¢rios   [ ]F2=Clientes      "
@  6, 23  SAY " ÀÄ[ ]Excluir       ÃÄ[ ]Pagar     [ ]F3=Funcionarios  "
@  7, 23  SAY "[ ]Clientes         ÃÄ[ ]Receber   [ ]F4=Prov/Desctos  "
@  8, 23  SAY " ÀÄ[ ]Excluir       ÃÄ[ ]Ext Banco [ ]F5=Bancos        "
@  9, 23  SAY "[ ]Funcionarios     ÃÄ[ ]Mov Caixa [ ]F6=Tabelas       "
@ 10, 23  SAY " ÀÄ[ ]Excluir       ÃÄ[ ]Caixa Men [ ]F7=Fornecedores  "
@ 11, 23  SAY "[ ]Cheques Pr‚      ÃÄ[ ]........  [ ]F8=Cheques       "
@ 12, 23  SAY " ÀÄ[ ]Excluir       ÃÄ[ ]........  [ ]F9=......        "
@ 13, 23  SAY "[ ]Bancos           ÃÄ[ ]........  [ ]F10=Grupos       "
@ 14, 23  SAY " ÃÄ[ ]Excluir       ÃÄ[ ]......    [ ]...............  "
@ 15, 23  SAY " ÀÄ[ ]Lan‡amentos   ÃÄ[ ].......   [ ]Contas           "
@ 16, 23  SAY "[ ]Grupos           ÃÄ[ ].......    ÃÄ[ ]Excluir       "
@ 17, 23  SAY "   [ ]Excluir       ÀÄ[ ].....      ÀÄ[ ]Baixar        "
@ 18, 23  SAY "[ ]Fornecedores     [ ]Rel Estoque [ ]Caixa            "
@ 19, 23  SAY "   [ ]Excluir       [ ]Rel Funcion [ ]..........       "
RETURN
